# Generated by Django 4.2.3 on 2023-08-02 12:28

from django.db import migrations, models
import django.db.models.deletion
import food_shop.food_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('chef_degree', models.CharField(choices=[('Pastry chef', 'Pastry chef'), ('Line cook', 'Line cook'), ('Chef', 'Chef'), ('Sous chef', 'Sous chef'), ('Culinary manager', 'Culinary manager'), ('Executive chef', 'Executive chef')], max_length=50)),
                ('cooked_dishes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[food_shop.food_app.models.is_only_letters])),
                ('description', models.TextField()),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('total_dishes', models.PositiveIntegerField(default=0)),
                ('total_breakfast_dishes', models.PositiveIntegerField(default=0)),
                ('total_lunch_dishes', models.PositiveIntegerField(default=0)),
                ('total_dinner_dishes', models.PositiveIntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.chef')),
            ],
        ),
    ]
