# Generated by Django 4.2.3 on 2023-08-02 13:09

from django.db import migrations, models
import food_shop.food_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_chef_ebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Dinner', 'Dinner')], max_length=10)),
                ('food_name', models.CharField(max_length=50, validators=[food_shop.food_app.models.is_only_letters])),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
