# Generated by Django 4.2.3 on 2023-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
