# Generated by Django 4.2.3 on 2023-08-02 13:19

from django.db import migrations, models
import food_shop.food_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=16, validators=[food_shop.food_app.models.is_old_enough]),
            preserve_default=False,
        ),
    ]
