# Generated by Django 4.2.3 on 2023-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookedfood',
            name='food_img',
            field=models.URLField(default='sero'),
            preserve_default=False,
        ),
    ]
