# Generated by Django 4.2.3 on 2023-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_cookedfood_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedfood',
            name='food_img',
            field=models.URLField(default='https://images.unsplash.com/photo-1604135307399-86c6ce0aba8e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1374&q=80'),
        ),
    ]
