# Generated by Django 4.2.3 on 2023-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_alter_cookedfood_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='url',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
