# Generated by Django 4.2.3 on 2023-08-08 17:43

from django.db import migrations, models
import food_shop.food_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_ebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[food_shop.food_app.models.is_old_enough]),
        ),
    ]
